### ISSUE TITLE
Webrtc link "https://webrtc.googlecode.com/svn/branches/3.52" at build instruction is deprecated.

### ISSUE THREAD

**Issue by strobe** [ipop-project/ipop-project.github.io#11]
```
svn: E160013: Unable to connect to a repository at URL 'https://webrtc.googlecode.com/svn/branches/3.52'
svn: E160013: 'https://webrtc.googlecode.com/svn/branches/3.52' path not found
```

**Comment by kcratie** [comment]
libjingle 3.52 has been deprecated. We are actively working on code modifications to synchronize with WebRTC. Regrettably, the build instructions will not work until those changes are completed.

**Comment by kcratie** [comment]
Updated build process available for source code in ipop-project/Tincan repository. It uses WebRTC branch head 57.
