### ISSUE TITLE
Building on distribution different from the Ubuntu.

### ISSUE THREAD

**Issue by ArhiChief** [ipop-project/ipop-project.github.io#17]
Hi there. I've try to build ipop-vpn on my Arch Linux machine. 

Following instructions from [here](https://github.com/ipop-project/ipop-project.github.io/wiki/Building-the-Code) I found what building dependent WebRTC components are impossible from scripts, so, I decide to build it myself using this [page](https://github.com/ipop-project/ipop-project.github.io/wiki/Building-the-WebRTC-lib-for-Linuxl). Everything works well but then I try to execute `./build/install-build-deps.sh` shell told me next:

`[arhichief@arhichief-pc src]$ ./build/install-build-deps.sh 
ERROR: Only Ubuntu 12.04 (precise), 14.04 (trusty),  14.10 (utopic), 15.04 (vivid), 15.10 (wily) and 16.04 (xenial)  are currently supported
`

So, how to build ipop-vpn on Arch Linux?

And one more. Is where any way to cross-compile ipop-vpn to another platforms, like ARM or MIPS and how?

**Comment by heythatsunfair** [comment]
I'd also like to know that. Why are there no general linux build instructions? Cross-compilation for Raspberry Pi and ARM devices would be great as well.

I hope that this project is popular one day and more developers will spend some time on it. The idea is GREAT and maybe it will even help to spread the word about Jabber and how useful it is!

**Comment by kcratie** [comment]
Hi All,
The existing release of IPOP-VPN was built using a now obsolete version of libjingle. Needless to say, it is challenging to build the tincan executable. However, the ipop-project is still actively being developed and we have a road map to have our next release use a current version of WebRTC as well as streamline the build process. We currently have a mid January release scheduled and we invite you to try the beta which will be available a couple weeks earlier.
Thanks for letting us know your interest and use for IPOP as it does influence our project's direction.
Regards.

**Comment by ashleeyoung** [comment]
Hi, any update on the beta or how we can participate and help? Thanks!

**Comment by kcratie** [comment]
The IPOP-VPN beta is now available and [instructions](https://github.com/ipop-project/ipop-project.github.io/wiki/Building-the-Code) on building and deploying are available.
Additionally, we have been able to build the Tincan executable for the Raspberry Pi. The first step is to [build](https://github.com/ipop-project/ipop-project.github.io/wiki/Build-WebRTC-Lib-for-Raspberry-Pi) the WebRTC libs. Afterwards, you would need to edit the Tincan Makefile to use the appropriate path for these libs. We will continue streamline this build process.

**Comment by vahid-dan** [comment]
Hi @ArhiChief @heythatsunfair;

We have already built IPOP for Raspberry Pi and Debian on ARMv7. Building for Arch Linux should be similar to those. You can find the instructions in the [wiki](https://github.com/ipop-project/ipop-project.github.io/wiki) and give it a shot! Please let us know about the results. :-)

Vahid

**Comment by isaactzab** [comment]
It would be interesting to be able to compile for android.

**Comment by vahid-dan** [comment]
Hi @isaactzab!

Thanks for your interest in IPOP! If you have root access on your Android device, it should be pretty straightforward to build IPOP for Android:

- First, you need to [build WebRTC libraries for IPOP](https://github.com/ipop-project/ipop-project.github.io/wiki/Build-WebRTC-Libraries,-Intro). Fortunately, there is [official support and documentation for that](https://webrtc.org/native-code/android/).

- Then, you can [build IPOP Tincan](https://github.com/ipop-project/ipop-project.github.io/wiki/Build-IPOP,-Intro). The instructions should be very similar to [what we have already done for Raspberry Pi](https://github.com/ipop-project/ipop-project.github.io/wiki/Build-IPOP-for-Raspbian-on-Raspberry-Pi). Just make sure you have copied the required WebRTC libraries and change the paths in the local copy [config.mk](https://github.com/ipop-project/Tincan/blob/master/trunk/build/config.mk) file according to them.

Please get back to us if you had any questions. We are really interested to know the results. :-)

Thanks,
Vahid

**Comment by vahid-dan** [comment]
We have recently added the support for Raspberry Pi Zero (ARMv6). This is the list of supported operating systems and platforms:

- Ubuntu 14.04 and 16.04, 64-bit
- Raspbian Stretch on Raspberry Pi 3, ARMv7
- Raspbian Stretch on Raspberry Pi Zero, ARMv6
- Microsoft Windows 10, 64-bit
- CentOS 7, 64-bit

If you're willing to build IPOP on other devices, we'd be more than happy to guide you through. :-)

Bests,
Vahid
