### ISSUE TITLE
ARM and x86 Linux builds

### ISSUE THREAD

**Issue by nwrkbiz** [ipop-project/ipop-project.github.io#18]
It woud be very handy if more precompiled Linux Architectures would be added.

This would make it pretty easy to use Social VPN for instance on an raspberry pi.

**Comment by renatof** [comment]
We're working on a new release which will catch up to the latest WebRTC
code base, and make the process of building *much* easier. The release is
slated for this month. Stay tuned.

**Comment by kcratie** [comment]
The precompiled WebRTC libs for Raspberry Pi (ARM7 32-bit) have been added to the Tincan repo.
