### ISSUE TITLE
Please send me a remittance

### ISSUE THREAD

**Issue by goldsoft8888** [ipop-project/ipop-project.github.io#20]
Please send me a remittance
I like this project, although there are some less satisfied with the place.
Such as isolation DHCP, OPENWRT following computer can only use a fixed IP address.
Does not support RFC5780,
But this project is really great.

I said before, would like to sponsor developers, for dinner, is a private nature, $ 300.
Small mind, the money is not much, but in our local, is a person's monthly salary.
Please send me a remittance. My English is very bad, this is GOOGLE translation.

-----------------
请给我一个汇款方式
我喜欢这个项目，虽然还有一些不太满意的地方。
比如隔离DHCP,  OPENWRT下面的电脑只能使用固定IP地址。
不支持RFC5780，
但这个项目真的很棒。

我以前说过，想赞助开发人员，用于聚餐，属于私人性质，300美元。
小小心意，钱不算多，但在我们当地，是一个人的月薪。
请给我一个汇款方式。我的英文很不好，这是用GOOGLE翻译的。

**Comment by renatof** [comment]
Hello,

Thank you for the kind words about the project - it's really appreciated!

It is kind of you to offer that to our developers. I am not sure if we
would be able to make it work - but thank you for the offer!

One thing that would also be a concrete way to help support the project is
if you could let us know (can be by email, and can be in Chinese) how you
have been using IPOP, for what applications, how many users, etc.

Best,
--rf

**Comment by goldsoft8888** [comment]
That's what I did,
In 1, he set up OPENFIRE SERVER STUN network, SERVER.
2, OPENWRT installation IPOP, compile their own. IPOP VPN FOR OPENWRT switching mode.
3, in a number of different locations to do two routing, each location of the original LAN, serial access.
(also in consideration of single arm routing, parallel access to the original LAN)
But in any case, there is a problem, that is, DHCP will cause confusion in the global broadcast, only the use of fixed IP, which must be resolved.
4, TURN SERVER cost is too high, has been erected, but can not be put into formal use.
Many of China's network is symmetric NAT+ multi WAN exports, ISP service providers such as CTT, mobile, radio and television, the Great Wall broadband, etc., there is no TURN is not available. RFC5780 should be a better solution.
Only a small number of ISP service providers can be used normally, must have a better penetration technology, and cheap.
5, is now being used only 10 IPOP FOR OPENWRT router, the future will be more.
At present, the main financial software, office software. Wireless routing +VPN+ print server.
6, in the future would like to IPOP virtualization, QEMU and so on the software package, but found that the performance of QEMU is too bad.
Thanks to all developers of this project.
 



我是这样实施的，
1、自己在公网架设了OPENFIRE SERVER、STUN SERVER。
2、OPENWRT 安装IPOP, 自己编译的。IPOP VPN FOR OPENWRT 交换模式。
3、在多个不同的地点做二级路由，每个地点原有局域网，串联接入。
（也在考虑做单臂路由，并联接入原有局域网）
但是任何方式，都有一个问题，就是DHCP会在全局广播造成混乱，只能使用固定IP，这个必须解决。
4、TURN SERVER 成本太高，已经架设，但不能投入正式使用。
中国的很多网络是对称NAT+多WAN出口，ISP服务商比如铁通、移动、广电、长城宽带等，没有TURN是无法使用的。RFC5780 应该是比较好的解决方案。
只有少数ISP服务商可以正常使用，必须有更好的穿透技术，并且廉价。


5、现在正在使用的只有10台 IPOP FOR OPENWRT路由器，以后会更多。
目前应用，主要是财务软件、办公软件。无线路由+VPN+打印服务器。


6、以后想将IPOP 虚拟化，用QEMU之类的软件封装，但是发现QEMU的性能太差了。


感谢这个项目的所有开发人员。 







------------------ 原始邮件 ------------------
发件人: "Renato Figueiredo";<notifications@github.com>;
发送时间: 2017年2月14日(星期二) 凌晨0:18
收件人: "ipop-project/ipop-project.github.io"<ipop-project.github.io@noreply.github.com>;
抄送: "好买卖"<xt0319@qq.com>; "Author"<author@noreply.github.com>;
主题: Re: [ipop-project/ipop-project.github.io] Please send me a remittance(#20)



Hello,

Thank you for the kind words about the project - it's really appreciated!

It is kind of you to offer that to our developers. I am not sure if we
would be able to make it work - but thank you for the offer!

One thing that would also be a concrete way to help support the project is
if you could let us know (can be by email, and can be in Chinese) how you
have been using IPOP, for what applications, how many users, etc.

Best,
--rf
