### ISSUE TITLE
How do I uninstall?

### ISSUE THREAD

**Issue by YellowOnion** [ipop-project/ipop-project.github.io#21]
I can't find any tutorial on how to uninstall.

**Comment by vahid-dan** [comment]
Hi @YellowOnion;

Thanks for your interest in IPOP and for your comment. :-)

To remove IPOP, its is safe to stop it first and then remove the IPOP execution directory.

If you're using Linux, to stop IPOP:
```
sudo killall ipop-tincan  
ps aux | grep -v grep | grep controller.Controller | awk '{print $2}' | xargs sudo kill -9 
```
If you are using [the install and config shell script](https://github.com/ipop-project/Release-Management/tree/master/Deployment/linux), we have recently added the remove option to the script. So you can easily remove it by running ```./ipop remove```.

Please let us know if you have any concern.

Bests,
Vahid
