### ISSUE TITLE
"Wiki" and "Projects" Links

### ISSUE THREAD

**Issue by vahid-dan** [ipop-project/ipop-project.github.io#25]
I think we don't need "Projects" links in any of our repositories and we also should remove "Wiki" from all the repositories except "ipop-project.github.io" and "Legacy-Documentation". That would be misleading. Those can be done in each repositories settings.

**Comment by kcratie** [comment]
Agreed, I've updated the repo settings accordingly. Issues should be reported via ipop-project.github.io
