### ISSUE TITLE
Windows installers

### ISSUE THREAD

**Issue by yurisa2** [ipop-project/ipop-project.github.io#33]
Hi! Congrats! Great Project!
Can´t find for my life the installers for windows, I see the last updated windows platform version is 16.08.1, but can´t download it from anywhere, all addresses are 404ing....

Thx!

**Comment by rcproam** [comment]
Yep there are no actual html links to any of the described pre-built binaries at https://github.com/ipop-project/Downloads

**Comment by vahid-dan** [comment]
@rcproam,

Thanks for your comment. You're right.

@yurisa2,

Sorry not to respond earlier. Let us know if you had any problem using IPOP.

Cheers,
Vahid

**Comment by vahid-dan** [comment]
Closed due to inactivity. Feel free to re-open it if needed.
